language: node_js
notifications:      # 每次构建的时候是否通知，如果不想收到通知邮箱，那就设置false吧
  email: false
node_js:
  - stable
  - 7
  - 6
  - 5
  - 4
#env: NODE_ENV=development
script:
  - npm run compile
  - npm run test
after_script:
  - npm install codecov
  - ./node_modules/.bin/nyc ./node_modules/.bin/ava --reporter=text-lcov
  - ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
  - ./node_modules/.bin/codecov -t decd7356-986f-4be4-a409-57ebf6c46796
#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
